---
title: 'The long hauler phenomena: Why COVID-19 mortality is only part of the story'
author: Daniel Lefever
date: '2020-07-27'
slug: the-long-hauler-phenomena-why-covid19-mortality-is-only-part-of-the-story
categories:
  - "COVID-19"
  - probability
  - statistics
tags:
  - "COVID-19"
  - model
  - probability
  - statistics
---


# Introduction
There has been quite a lot of focus on using the infection fatality rate (IFR)^[The number of deaths over the total number of infections] of COVID-19 to quantify the disease severity. The first thing to note here is that despite the math being simple, this is surprisingly hard to calculate^[This [page](https://ourworldindata.org/mortality-risk-covid#country-by-country-data-on-mortality-risk-of-the-covid-19-pandemic) goes into the nuances for why this is.]. One reason is that the total number of cases is unknown. However even if that were known, the actual number is not static^[In other words, the IFR is influenced by many factors such as the available treatment and the health of the population.]. With that said, the CDC's current best guess of the overall infection fatality rate (IFR) is [0.65%](https://www.cdc.gov/coronavirus/2019-ncov/hcp/planning-scenarios.html). When you further break this down according to age, the estimated IFR of younger people is much smaller. 

```{r naive_binary_mortality, fig.cap="Binary outcome"}
library(tidyverse)
library(ggplot2)
library(cowplot)
plot_data <- tibble(status=c("Recovered", "Dead"), value=c(.9935, .0065))

ggplot(data=plot_data, aes(x=status, y=value)) + 
  geom_col() + 
  scale_y_continuous(labels = scales::percent_format()) + 
  theme_cowplot() + 
  theme(text = element_text(face="bold")) + labs(x="", y="Percentage Infected with COVID-19")


```

Lets forgot about the demographics and stick with a single IFR 0.65% for the moment. Since only 0.65% of people die, then that must mean 99.35% of people will ultimately recover. You can see^[Not that I think anyone needs help visualizing how large of a difference this is, I just like pictures.] in \@ref(fig:naive_binary_mortality) that the recovered dwarfs deaths, to the point where it's hard to even see the deaths at all. The issue here is that recovery can be misleading. When I think of recovery, I think of a return to baseline^[For example, when I get a cold, I'm miserable for anywhere from 3-14 days. After that, I'm back to normal. Sometimes, even better because of all the rest.]. That's unfortunately just not always the case with COVID-19. 


# The effects from COVID-19 can be permanent and severe
## Short-term consequences of infection can have long-term effects
The recovered group would include people who have had acute [kidney](https://jasn.asnjournals.org/content/31/7/1380) and [cardiac](https://www.nature.com/articles/s41569-020-0360-5#further-reading) injuries as a results of COVID-19, but ultimately went on to survive. There are also people who have had [strokes](https://www.nejm.org/doi/full/10.1056/NEJMc2009787#article_citing_articles). Some have even needed to have [limbs amputated](https://www.washingtonpost.com/nation/2020/04/20/nick-cordero-leg-coronavirus/) due to [complications of COVID-19](https://www.kxan.com/news/coronavirus/covid-19-survivor-who-had-most-of-his-fingers-amputated-this-can-happen-to-you/). One young woman needed a [lung transplant](https://www.npr.org/sections/health-shots/2020/06/12/875486356/first-known-u-s-lung-transplant-for-covid-19-patient-performed-in-chicago). These people would also be included in the recovered group.  

The [concensus](https://www.sciencemag.org/news/2020/04/how-does-coronavirus-kill-clinicians-trace-ferocious-rampage-through-body-brain-toes) is that pretty much all organs are fair game to COVID-19. One of the ways COVID-19 can cause so much havoc is through hypercoagulability^[Excessive blood clotting. You can think of it like turning the consistency of blood from that of cooking oil to jelly. ]. This would explain why COVID-19, a *respiratory disease*, could bring on things like heart attacks^[I thought this totally bizarre at first, and didn't immediately see why this virus could cause a seemingly random assortment of diseases. It makes much more sense when you consider the potential consequences of hypercoagulation. This would be much more severe in populations with a high prevalence of diseases like atherosclerosis. You could imagine that this hypercoagulation could be enough to cause a heart-attack or stroke in someone whose vascular system is already clogged.]. 

## Early suggestions of chronic, long term consequences of infections
There's also the possibility COVID-19 can cause or certainly contribute to chronic conditions. For example, COVID-19 [can damage the heart](https://jamanetwork.com/journals/jamacardiology/fullarticle/2768915) but not to the point where it causes a heart attack.
For example, say COVID-19 causes some damage to the heart but not enough to actually cause a heart attack. The same thing could happen with the [kidneys](https://www.kidney-international.org/article/S0085-2538(20)30532-9/fulltext#secsectitle0010). This could potentially lead to an increased susceptibility for heart and kidney disease in the future. 

I should note here that it isn't clear just how much of the organ damage caused by COVID-19 is permanent. That is why I used the term **suggestions** in the sub-section title. The only way to know for sure^[As sure as anyone can be about this sort of thing. Like, say the certainty surrounding the link between smoking and lung cancer.] is to wait and see^[SARS-CoV-2 was only discovered ~8 months ago, and it took a couple months for the potential global impact of this virus to become apparent. Since chronic diseases can take years to decades to develop, there just hasn't been enough time to know the impact of COVID-19 in this context.]. That, however, is an answer that literally no-one is satisfied with. My best guess^[I mean guess here literally, because that's what it is.] is that there will COVID-19 infection will be a risk factor for some chronic diseases. How much of one? Again, I can only guess here, but I'd imagine the magnitude will have a huge range^[In other words, I expect it to vary similarly to the disease severity: for some people it will be negligible, for others it may be substantial.].


[risk factors](https://www.nature.com/articles/s41586-020-2521-4_reference.pdf)

# The long-haulers
[long haulers](https://news.berkeley.edu/2020/07/08/from-lung-scarring-to-heart-damage-covid-19-may-leave-lingering-marks/)


